version: '3'
services:
  redis:
    image: 'redis'
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    build:
      dockerfile: Dockerfile.Dev
      context: ./nginx
    ports:
      - '4001:80'
    restart: always
    depends_on:
      - client
      - api
  client:
    build:
      dockerfile: Dockerfile.Dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.Dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build:
      dockerfile: Dockerfile.Dev
      context: ./worker
    volumes:
       - /app/node_modules
       - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
